---
kind: ReplicationController
apiVersion: v1beta3
metadata: 
  name: framework
  labels: 
    name: framework
spec: 
  replicas: 2
  selector: 
    name: framework
  template: 
    metadata: 
      labels: 
        name: framework
    spec: 
      containers: 
        - 
          name: framework
          image: 172.16.16.15:5000/trogdor-framework:1
          ports: 
            - 
              containerPort: 9080
              protocol: TCP
