---
kind: ReplicationController
apiVersion: v1beta3
metadata: 
  name: load-generator-master
  labels: 
    name: load-generator-master
spec: 
  replicas: 1
  selector: 
    name: load-generator-master
  template: 
    metadata: 
      labels: 
        name: load-generator-master
    spec: 
      containers: 
        - 
          name: load-generator-master
          image: 172.16.16.15:5000/trogdor-load-generator
          command: 
            - locust
            - -f
            - /scripts/locustfile.py
            - --master
            - --host=http://framework:9080
          ports: 
            - 
              containerPort: 8089
              protocol: TCP
            - 
              containerPort: 5557
              protocol: TCP
            - 
              containerPort: 5558
              protocol: TCP
          env: 
            - 
              name: INFLUXDB_HOST
              value: influxdb
            - 
              name: INFLUXDB_PORT
              value: "8086"
            - 
              name: INFLUXDB_USER
              value: root
            - 
              name: INFLUXDB_PASSWORD
              value: root
            - 
              name: INFLUXDB_NAME
              value: k8s
      nodeSelector:
        region: zone1
