---
kind: Service
apiVersion: v1beta3
metadata:
  name: load-generator-master
  labels:
    name: load-generator-master
spec:
  ports:
    -
      port: 8089
      targetPort: 8089
      name: locust-http
      protocol: TCP
    -
      port: 5557
      targetPort: 5557
      name: locust-slavecomm
      protocol: TCP
    -
      port: 5558
      targetPort: 5558
      name: locust-slavecomm2
      protocol: TCP
  publicIPs:
    - 172.16.16.20
  selector:
    name: load-generator-master
