apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: grafana-v1
  namespace: default
  labels:
    k8s-app: Grafana
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: Grafana
    version: v1
  template:
    metadata:
      labels:
        k8s-app: Grafana
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: 172.16.16.15:5000/grafana
          name: grafana
          env:
            - name: GRAFANA_DEFAULT_DASHBOARD
              value: /dashboard/file/loadtest.json
            - name: INFLUXDB_EXTERNAL_URL
              value: http://172.16.16.16:8086/db/
            - name: INFLUXDB_HOST
              value: influxdb
            - name: INFLUXDB_PORT
              value: "8086"
