apiVersion: v1beta3
kind: Service
metadata:
  name: grafana
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
spec:
  ports:
    - port: 8002
      targetPort: 8080
  selector:
    k8s-app: Grafana
  publicIPs:
    - 172.16.16.20
